version: "3.8"

networks:
  app-network:
    driver: bridge

services:
  superset:
    env_file:
      - superset.env
    image: "ddp-superset:0.2"
    container_name: superset-oauth
    networks:
      - app-network
    ports:
      - 80:8088
    depends_on:
      - db
      - superset_cache
    volumes:
      - ./host_data:/host_data/
      - ./scripts:/scripts/
      - ./logs:/logs/

  db:
    image: postgres
    env_file:
      - superset.env
    networks:
      - app-network
    volumes:
      - ./dbstartup:/docker-entrypoint-initdb.d/

  superset_cache:
    image: redis
    networks:
      - app-network

  celery-beat:
    image: ddp-superset:0.2
    command: celery --app=superset.tasks.celery_app:app beat -s /app/superset_home/celerybeat_schedule
    env_file:
      - superset.env
    depends_on:
      - superset
    restart: always
    networks:
      - app-network

  celery-worker:
    image: ddp-superset:0.2
    command: celery --app=superset.tasks.celery_app:app worker --pool=prefork -O fair -c 4
    env_file:
      - superset.env
    depends_on:
      - superset
    restart: always
    networks:
      - app-network

  celery-flower:
    image: ddp-superset:0.2
    command: celery --app=superset.tasks.celery_app:app flower
    env_file:
      - superset.env
    depends_on:
      - superset
    restart: always
    ports:
      - 5555:5555
    networks:
      - app-network
