version: "3.8"

networks:
  app-network:
    driver: bridge

services:
  superset:
    env_file:
      - superset.env
    image: "ddp-superset:0.1"
    networks:
      - app-network
    ports:
      - 8088:8088
    depends_on:
      - db
      - superset_cache

  db:
    image: postgres
    env_file:
      - superset.env
    networks:
      - app-network
    volumes:
      - ./dbstartup:/docker-entrypoint-initdb.d/

  superset_cache:
    image: redis
    networks:
      - app-network
