version: "3.8"

networks:
  app-network:
    driver: bridge

services:
  superset:
    env_file:
      - superset.env
    image: "ddp-superset:0.1"
    networks:
      - app-network
    ports:
      - 8088:8088
    depends_on:
      - db
      - superset_cache

  db:
    image: postgres
    env_file:
      - superset.env
    networks:
      - app-network
    volumes:
      - ./dbstartup:/docker-entrypoint-initdb.d/

  superset_cache:
    image: redis
    networks:
      - app-network

  celery-beat:
    image: apache/superset:2.0.1-dev
    command: celery --app=superset.tasks.celery_app:app beat -s /app/superset_home/celerybeat_schedule
    depends_on:
      - superset
    restart: always
    networks:
      - app-network

  celery-worker:
    image: apache/superset:2.0.1-dev
    command: celery --app=superset.tasks.celery_app:app worker --pool=prefork -O fair -c 4
    depends_on:
      - superset
    restart: always
    networks:
      - app-network

  celery-flower:
    image: apache/superset:2.0.1-dev
    command: celery --app=superset.tasks.celery_app:app flower
    depends_on:
      - superset
    restart: always
    ports:
      - 5555:5555
    networks:
      - app-network
