# Starting with the apache/superset base image
FROM apache/superset:3.1.3

# Switching to root to install the required packages
USER root

# Upgrade pip
RUN pip install --upgrade pip

# Install the necessary Python packages
RUN pip install --no-cache gevent psycopg2-binary redis celery flower pytz
RUN pip install --upgrade urllib3 requests botocore boto3 authlib python-dotenv
RUN pip install --upgrade sqlalchemy-bigquery pandas_gbq google-auth

# Switching back to using the `superset` user
USER superset
